#!/bin/bash
# Hugo build script for docs.
EXTRA_ARGS=""
COMPONENT_PATH="documents"
LOCAL_MODE="no"
MODE="served"
TARGET="debug"


# Parse arguments.
while [ "$#" -ne 0 ]; do
  arg=$1
  shift

  case "${arg}" in
    --drafts)
      EXTRA_ARGS="${EXTRA_ARGS} --buildDrafts"
      ;;

    --local)
      LOCAL_MODE="yes"
      ;;

    --path)
      COMPONENT_PATH=$1
      shift
      ;;

    --target)
      TARGET=$1
      shift
      ;;

    --uglyURLs)
      EXTRA_ARGS="${EXTRA_ARGS} --uglyURLs"
      MODE="portable"
      ;;

    *)
      echo "Unable to parse argument '${arg}'!"
      exit 1
  esac
done


### MAIN ###
DEST="${PWD}/out/dist/${TARGET}/${COMPONENT_PATH}/${MODE}"

if [ "${LOCAL_MODE}" == "yes" ]; then
  EXTRA_ARGS="${EXTRA_ARGS} --watch server"
fi

cd "${COMPONENT_PATH}"

# Build styles.
mkdir -p themes/snow-fox/static/css
lessc --relative-urls themes/snow-fox/_less/core.less \
  > themes/snow-fox/static/css/core.css

# Build graphs.
_build/graphs

# Build site.
hugo --destination "${DEST}" ${EXTRA_ARGS} || exit 1
