#!/bin/bash
#  Render graphs written in dot files.


DATA="./data"
STATIC="./static"


dot_svg() {
  dir=$(dirname "$1")
  name=$(basename "$1" .dot)

  mkdir -p "${STATIC}/${dir}"
  dot -Tsvg "${DATA}/$1" > "${STATIC}/${dir}/${name}.svg"
}


dot_svg "references/advanced/drains.dot"
dot_svg "references/advanced/loop.dot"
dot_svg "references/advanced/sources.dot"
